"""init

Revision ID: eb95e4544336
Revises: 
Create Date: 2021-10-23 20:44:52.465108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb95e4544336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('positivity', sa.String(length=8), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_component_name'), 'component', ['name'], unique=False)
    op.create_table('product',
    sa.Column('barcode', sa.String(length=15), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('proteins', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('fats', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('carbohydrates', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('calories', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('mass', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('package', sa.Text(), nullable=False),
    sa.Column('is_gmo', sa.Boolean(), nullable=False),
    sa.Column('is_organic', sa.Boolean(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_vegan', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blacklist', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['component'], ['component.id'], name='fk_products_components_component_component_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product'], ['product.barcode'], name='fk_products_components_product_product_barcode', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_components')
    op.drop_table('user')
    op.drop_table('product')
    op.drop_index(op.f('ix_component_name'), table_name='component')
    op.drop_table('component')
    # ### end Alembic commands ###
